version: '3'
services:
  db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=bossabox
    volumes:
      - ./config/db.sql:/docker-entrypoint-initdb.d/db.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
    depends_on:
      - db
